var docs = [
	{"key":"Query" , "content":""},
	{"key":"Tehran" , "content":"Tehran is the capital of Iran and Tehran Province. With a population of around 8.7 million in the city and 15 million in the larger metropolitan area of Greater Tehran, Tehran is the most populous city in Iran and Western Asia , and has the third - largest metropolitan area in the Middle East ( surpassed by Cairo and Istanbul )."},
	{"key":"Shiraz" , "content":"Shiraz is the fifth-most-populous city of Iran and the capital of Fars Province also known as Pars and Persis ( Persia ). At the 2016 census , the population of the city was 1,869,001 and its built-up area with \" Shahr-e Jadid-e Sadra \" ( Sadra New Town ) was home to 1,565,572 inhabitants . Shiraz is located in the southwest of Iran on the \" Rudkhaneye Khoshk \" ( The Dry River ) seasonal river . It has a moderate climate and has been a regional trade center for over a thousand years . Shiraz is one of the oldest cities of ancient Persia ."},
	{"key":"Tabriz" , "content":"Tabriz  is the most populated city in northwestern Iran , one of the historical capitals of Iran and the present capital of East Azerbaijan province . It is the fourth most populous city in Iran . Located in the Quru River valley , in Iran's historic Azerbaijan region , between long ridges of volcanic cones in the Sahand and Eynali mountains , Tabriz's elevation ranges between 1,350 and 1,600 metres ( 4,430 and 5,250 ft ) above sea level . The valley opens up into a plain that gently slopes down to the eastern shores of Lake Urmia , 60 kilometres ( 37 miles ) to the west ."},
	{"key":"New York City ( NYC )" , "content":"New York City ( NYC ), often called The City or simply New York ( NY ), is the most populous city in the United States. With an estimated 2019 population of 8,336,817 distributed over about 302.6 square miles ( 784 km2 ) , New York is also the most densely populated major city in the United States . Located at the southern tip of the U.S. state of New York , the city is the center of the New York metropolitan area , the largest metropolitan area in the world by urban landmass ."},
	{"key":"Washington DC" , "content":"Washington DC formally the District of Columbia and also known as DC or Washington , is the capital city of the United States of America . Founded after the American Revolution as the seat of government of the newly independent country , Washington was named after George Washington , the first president of the United States and a Founding Father ."},
	{"key":"Barcelona" , "content":"Barcelona is a city on the coast of northeastern Spain . It is the capital and largest city of the autonomous community of Catalonia , as well as the second most populous municipality of Spain . With a population of 1.6 million within city limits , its urban area extends to numerous neighbouring municipalities within the Province of Barcelona and is home to around 4.8 million people , making it the fifth most populous urban area in the European Union ."},
	{"key":"Madrid" , "content":"Madrid is the capital and most populous city of Spain . The city has almost 3.3 million inhabitants and a metropolitan area population of approximately 6.5 million . It is the second-largest city in the European Union ( EU ), surpassed only by Berlin , and its monocentric metropolitan area is the second largest in the EU . The municipality covers 604.3 km2 ( 233.3 sq mi )."},
	{"key":"Paris" , "content":"Paris is the capital and most populous city of France , with a population of 2,148,271 residents ( official estimate , 1 January 2020 ) in an area of 105 square kilometres ( 41 square miles ). Since the 17th century , Paris has been one of Europe's major centres of finance , diplomacy , commerce , fashion , science and arts ."},
	{"key":"Marseille" , "content":"Marseille was an important European trading centre and remains the main commercial port of the French Republic . Marseille is now France's largest city on the Mediterranean coast and the largest port for commerce , freight and cruise ships ."},
	{"key":"Berlin" , "content":"Berlin is the capital and largest city of Germany by both area and population . Its 3,769,495 (2019) inhabitants make it the most populous city proper of the European Union . The city is one of Germany's 16 federal states . It is surrounded by the state of Brandenburg , and contiguous with Potsdam, Brandenburg's capital . The two cities are at the center of the Berlin-Brandenburg capital region , which is , with about six million inhabitants and an area of more than 30,000 km² , Germany's third-largest metropolitan region after the Rhine-Ruhr and Rhine-Main regions ."}
]
module.exports = { docs }